### ISSUE TITLE
Brush stuck painting when mouse leaves Canvas

### ISSUE THREAD

**Issue by chevreaux** [chicory-pizza/chicory-data#88]
Since mouse events are only detected when the mouse in on the canvas, if you go off the side and let go of mouse, you will still be painting when you return to canvas. Ideally painting should only occur when mouse is down.

This is presumably a result of fabdab9509bbc2c394deb7e560fada144c9b3316.

**Comment by ngyikp** [comment]
That commit didn't introduce a new bug, the issue is due to us binding the mouseup event to a specific element and expecting the mouseup event to run to stop painting.

However, this doesn't work when the mouse is outside the canvas as the mouseup event is contained inside that element and won't run. This is also an issue when using keyboard shortcuts to switch tool.
